server:
  port: ${PORT:8081}


spring:
  datasource:
    # url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/camisasdb}
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:Exito2025!}
  jpa:
    hibernate:
      ddl-auto: update   # usamos Flyway para crear/sembrar
    open-in-view: true
    properties:
      hibernate.format_sql: true
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

# Swagger UI: http://localhost:8081/swagger-ui/index.html


